=== uo294258/sew/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horainicio" />
				<xs:element ref="numvueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria" />
				<xs:element ref="galeriavideos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horainicio" type="xs:time" />
	<xs:element name="numvueltas">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="enlace" type="xs:anyURI" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriavideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadasfinales" />
				<xs:element ref="numerosector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="medida" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadasfinales">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="numerosector">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
</xs:schema>

=== uo294258/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<circuito
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

        <nombre>Circuit Of The Americas</nombre>
        <longitudCircuito medida="km">5.513</longitudCircuito>
        <anchura medida="m">14</anchura>
        <fecha>2024-04-14</fecha>
        <horainicio>21:00:00</horainicio>
        <numvueltas>56</numvueltas>
        <localidad>Austin</localidad>
        <pais>Estados Unidos</pais>
        <referencias> 
            <referencia enlace="https://circuitoftheamericas.com/">Pagina Oficial</referencia>
            <referencia enlace="https://es.wikipedia.org/wiki/Circuito_de_las_Am%C3%A9ricas"> Wikipedia </referencia>
            <referencia enlace="https://www.formula1.com/en/racing/2024/united-states/circuit">Pagina Formula 1 </referencia>
        </referencias>
        <galeria> 
            <imagen archivo="panorama.jpg">Panorama</imagen>
            <imagen archivo="circuito.png">Circuito</imagen>
        </galeria>
        <galeriavideos> 
            <video archivo="videoCircuito.mp4">Video Circuito</video>  
        </galeriavideos>
        <coordenadas>
            <longitud> -97.6422641 </longitud>
            <latitud>  30.1335256 </latitud>
            <altitud medida="m"> 157.5727233   </altitud>
        </coordenadas>
        <tramos>
            <tramo>
                <distancia medida="m"> 627.56</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6371269 </longitud>
                    <latitud> 30.1300454  </latitud>
                    <altitud medida="m"> 184   </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 35.24</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6367843 </longitud>
                    <latitud> 30.1301578  </latitud>
                    <altitud medida="m"> 185   </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 190.10</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6373575 </longitud>
                    <latitud> 30.1317940  </latitud>
                    <altitud medida="m"> 169  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 67.48</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6372017 </longitud>
                    <latitud> 30.1323857  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 40.51</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6369234 </longitud>
                    <latitud> 30.1326592  </latitud>
                    <altitud medida="m"> 165  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 191.81</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6352336 </longitud>
                    <latitud> 30.1335756  </latitud>
                    <altitud medida="m"> 168  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 84.57</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6348316 </longitud>
                    <latitud> 30.1342520  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m">33.76</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6345685   </longitud>
                    <latitud> 30.1344530  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 54.35</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6340516 </longitud>
                    <latitud> 30.1346506  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m">37.91</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6337930 </longitud>
                    <latitud> 30.1349079  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 65.05</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6336688 </longitud>
                    <latitud> 30.1354830  </latitud>
                    <altitud medida="m"> 165  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 48.39</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6334156 </longitud>
                    <latitud> 30.1358591  </latitud>
                    <altitud medida="m"> 165  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 59.99</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6329027 </longitud>
                    <latitud> 30.1361598  </latitud>
                    <altitud medida="m"> 166  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 49.52</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6323895 </longitud>
                    <latitud> 30.1361966  </latitud>
                    <altitud medida="m"> 167  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 64.29</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6317864 </longitud>
                    <latitud> 30.1359471  </latitud>
                    <altitud medida="m"> 168  </altitud>
                </coordenadasfinales>
                <numerosector> 1 </numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 61.65</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6311905 </longitud>
                    <latitud> 30.1357426  </latitud>
                    <altitud medida="m"> 168  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 44.79</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6307746 </longitud>
                    <latitud> 30.1359240  </latitud>
                    <altitud medida="m"> 167  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 91.37</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6301394 </longitud>
                    <latitud> 30.1365351  </latitud>
                    <altitud medida="m"> 170  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 32.11</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6298251 </longitud>
                    <latitud> 30.1366326  </latitud>
                    <altitud medida="m"> 172  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 32.88</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6294881 </longitud>
                    <latitud> 30.1365826  </latitud>
                    <altitud medida="m"> 174  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 55.32</distancia>
                <coordenadasfinales>   
                    <longitud> -97.6291208 </longitud>
                    <latitud> 30.1361997  </latitud>
                    <altitud medida="m"> 177  </altitud>
                </coordenadasfinales>
                <numerosector> 2</numerosector>
            </tramo>
            <tramo>
                <distancia medida="m"> 33.23</distancia>
                <coordenadasfinales>
